version: "2"
services:
  webserver:
    image: livesporttalk-web-server
    ports:
      - "80:80"
    volumes:
      - ./server:/var/www/html
      - ./dist:/var/www/html/dist
    environment:
      SITE_URL: http://localhost